### ISSUE TITLE
make: python3.7: Command not found

### ISSUE THREAD

**Issue by Nightwing9** [BluRosie/hg-mega-evolution#5]
When trying to build the test.nds, I get the following error message:

**-e rom.nds Decompression successful!!
tools/narchive.exe extract base/root/a/0/2/8 -o build/a028/ -nf
python3.7 scripts/make.py
make: python3.7: Command not found
Makefile:84: recipe for target 'all' failed
make: *** [all] Error 127**

I have Python 3.7.6 installed and made sure to check Add to Path before installing.

**Comment by BluRosie** [comment]
how do you have it installed?  python, python3, or python3.7?
run python --version to check 
and then python3 --version, etc

**Comment by Nightwing9** [comment]
I downloaded 3.7.6 executable installer from the official site: 
https://www.python.org/downloads/release/python-376/
Then I ran the executable, checked Add to Path and installed. Not sure what you mean by python, python3 or python3.7, this stuff is fairly new to me.

**Comment by BluRosie** [comment]
go into wsl (shift + right click) and run `python --version` really quickly

**Comment by Nightwing9** [comment]
I typed python3 --version and it says python 3.6.9 is installed. I don't know why that is.

**[Edit]:** Python3.7 --version says that 3.7.5 is installed. Now when I try to build the test.nds, the previous error doesn't happen and now I get this:
-e rom.nds Decompression successful!!
tools/narchive.exe extract base/root/a/0/2/8 -o build/a028/ -nf
python3.7 scripts/make.py
Decompress arm9.
Inserting code.
tools/armips.exe armips/global.s
tools/narchive.exe extract base/root/a/0/2/7 -o build/text -nf
python3.7 scripts/build.py
generating gfx data for folder 000...
generating gfx data for folder 001...
generating gfx data for folder 002...
generating gfx data for folder 003...
generating gfx data for folder 004...
generating gfx data for folder 005...
generating gfx data for folder 006...
generating gfx data for folder 007...
generating gfx data for folder 008...
generating gfx data for folder 009...
generating gfx data for folder 010...
generating gfx data for folder 011...
generating gfx data for folder 012...
generating gfx data for folder 013...
generating gfx data for folder 014...
generating gfx data for folder 015...
generating gfx data for folder 016...
generating gfx data for folder 017...
generating gfx data for folder 018...
generating gfx data for folder 019...
generating gfx data for folder 020...
generating gfx data for folder 021...
generating gfx data for folder 022...
generating gfx data for folder 023...
generating gfx data for folder 024...
generating gfx data for folder 025...
generating gfx data for folder 026...
generating gfx data for folder 027...
generating gfx data for folder 028...
generating gfx data for folder 029...
generating gfx data for folder 030...
generating gfx data for folder 031...
generating gfx data for folder 032...
generating gfx data for folder 033...
generating gfx data for folder 034...
generating gfx data for folder 035...
generating gfx data for folder 036...
generating gfx data for folder 037...
generating gfx data for folder 038...
generating gfx data for folder 039...
generating gfx data for folder 040...
generating gfx data for folder 041...
generating gfx data for folder 042...
generating gfx data for folder 043...
generating gfx data for folder 044...
generating gfx data for folder 045...
generating gfx data for folder 046...
generating gfx data for folder 047...
generating gfx data for folder 048...
generating gfx data for folder 049...
generating gfx data for folder 050...
generating gfx data for folder 051...
generating gfx data for folder 052...
generating gfx data for folder 053...
generating gfx data for folder 054...
generating gfx data for folder 055...
generating gfx data for folder 056...
generating gfx data for folder 057...
generating gfx data for folder 058...
generating gfx data for folder 059...
generating gfx data for folder 060...
generating gfx data for folder 061...
generating gfx data for folder 062...
generating gfx data for folder 063...
generating gfx data for folder 064...
generating gfx data for folder 065...
generating gfx data for folder 066...
generating gfx data for folder 067...
generating gfx data for folder 068...
generating gfx data for folder 069...
generating gfx data for folder 070...
generating gfx data for folder 071...
generating gfx data for folder 072...
generating gfx data for folder 073...
generating gfx data for folder 074...
generating gfx data for folder 075...
generating gfx data for folder 076...
generating gfx data for folder 077...
generating gfx data for folder 078...
generating gfx data for folder 079...
generating gfx data for folder 080...
generating gfx data for folder 081...
generating gfx data for folder 082...
generating gfx data for folder 083...
generating gfx data for folder 084...
generating gfx data for folder 085...
generating gfx data for folder 086...
generating gfx data for folder 087...
generating gfx data for folder 088...
generating gfx data for folder 089...
generating gfx data for folder 090...
generating gfx data for folder 091...
generating gfx data for folder 092...
generating gfx data for folder 093...
generating gfx data for folder 094...
generating gfx data for folder 095...
generating gfx data for folder 096...
generating gfx data for folder 097...
Traceback (most recent call last):
  File "scripts/build.py", line 164, in <module>
    build_icon()
  File "scripts/build.py", line 109, in build_icon
    shutil.copy("data/rawdata/first files from a020/" + i, "narc/pokemonicon/" + i)
  File "/usr/lib/python3.7/shutil.py", line 249, in copy
    copymode(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 144, in copymode
    chmod_func(dst, stat.S_IMODE(st.st_mode))
PermissionError: [Errno 1] Operation not permitted: 'narc/pokemonicon/0_000'
Makefile:84: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by BluRosie** [comment]
alright awesome, follow these instructions really quickly:


Open cmd.exe
Type ``wsl -u root``
Type ``passwd`` and change the password
Type ``exit``

Open wsl by pressing Windows key + R and typing ``wsl``
Type su and enter the new password you changed before
Run the following commands:
```
export DEVKITPRO=/opt/devkitpro
echo "export DEVKITPRO=$DEVKITPRO" >> ~/.bashrc
export DEVKITARM=$DEVKITPRO/devkitARM
echo "export DEVKITARM=$DEVKITARM" >> ~/.bashrc
```then recompile

**Comment by Nightwing9** [comment]
What do you mean by then recompile? Is that a command that follows the previous four?

**Comment by BluRosie** [comment]
yea rerun ``make``

**Comment by Nightwing9** [comment]
Ran those commands in WSL, then ran make in the Mega Evo folder and still got the same error. 

[Edit]: Did a restart of my computer and the problem seems to be fixed. The test.nds is now created.
[Edit 2]: Where do I get the Mega stones for the player character? I know how to apply them to trainers, but for the PC do I need to purchase them or find them or hex edit the save file?

**Comment by BluRosie** [comment]
perfect, glad to hear that it's working!

i changed nothing else other than adding the mega stones--if you want, [here's a link to a .sav file with the stones hex edited in](https://mega.nz/file/fuBgXJDA#tcHUyNi7S2UPGx1jUSF0zNtimRkk5u4wCCUlmw-DO80)
